{{- if .Values.bunkerweb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bunkerweb.fullname" . }}-internal
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    bunkerweb.io/component: "bunkerweb"
  {{- if and .Values.bunkerweb.service.headless (ne .Values.bunkerweb.service.headless false) }}
  clusterIP: None
  {{- else }}
  type: ClusterIP
  ports:
    - name: bwapi
      protocol: TCP
      port: 5000
      targetPort: 5000
  {{- end }}
---
{{- if .Values.scheduler.usePrometheusExporter -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bunkerweb.fullname" . }}-metrics
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
    bunkerweb.io/component: "bunkerweb-metrics"
spec:
  type: ClusterIP
  selector:
    bunkerweb.io/component: "bunkerweb"
  ports:
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
{{- end }}
{{- end }}