{{- if and .Values.bunkerweb.enabled .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bunkerweb.fullname" . }}-external
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  selector:
    bunkerweb.io/component: "bunkerweb"
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortHttp }}
      nodePort: {{ .Values.service.nodePortHttp }}
      {{- end }}
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePortHttps }}
      nodePort: {{ .Values.service.nodePortHttps }}
      {{- end }}
{{- end }}