{{- if and .Values.bunkerweb.enabled (eq .Values.bunkerweb.kind "StatefulSet") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "bunkerweb.fullname" . }}-internal
  replicas: {{ .Values.bunkerweb.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
      bunkerweb.io/component: "bunkerweb"
  template:
    metadata:
      annotations:
        {{- if eq .Values.bunkerweb.enableInstance true }}
        bunkerweb.io/INSTANCE: "yes"
        {{- end }}
        {{- with .Values.bunkerweb.podAnnotations }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.bunkerweb.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "bunkerweb"
    spec:
    {{- with .Values.bunkerweb.affinity }}
      affinity:
      {{- toYaml . | nindent 8}}
    {{- end }}
      {{- if not .Values.bunkerweb.affinity}}
      affinity:
      {{- end }}
      {{- if eq .Values.bunkerweb.podAntiAffinityPreset "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  bunkerweb.io/component: "bunkerweb"
      {{- else if eq .Values.bunkerweb.podAntiAffinityPreset "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  bunkerweb.io/component: "bunkerweb"
      {{- end }}
      containers:
        - name: bunkerweb
          image: {{ .Values.bunkerweb.repository }}:{{ .Values.bunkerweb.tag }}
          imagePullPolicy: {{ .Values.bunkerweb.pullPolicy }}
          {{- with .Values.bunkerweb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bunkerweb.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 5000
              name: bwapi
            - containerPort: 8080
            - containerPort: 8443
            {{- if and .Values.bunkerweb.usePrometheusExporter }}
            - containerPort: 9113
              name: metrics
            {{- end }}
          env:
            # Mandatory for k8s integration
            - name: KUBERNETES_MODE
              value: "yes"
            # DNS resolver
            - name: DNS_RESOLVERS
              value: "{{ .Values.settings.misc.dnsResolvers }}"
            # Internal subnet(s) + localhost
            - name: API_WHITELIST_IP
              value: "{{ .Values.settings.misc.apiWhitelistIp }}"
            {{- include "bunkerweb.redisEnv" . | nindent 12 }}
            {{- if .Values.ui.logs.enabled }}
            - name: ACCESS_LOG_1
              value: "syslog:server={{ include "bunkerweb.syslogAddress" . }},tag=bunkerweb_access"
            - name: ERROR_LOG_1
              value: "syslog:server={{ include "bunkerweb.syslogAddress" . }},tag=bunkerweb"
            {{- end }}
          {{- if .Values.bunkerweb.extraEnvs }}
            {{- toYaml .Values.bunkerweb.extraEnvs | nindent 12 }}
          {{- end }}
          {{- with .Values.bunkerweb.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bunkerweb.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.bunkerweb.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bunkerweb.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
