apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bunkerweb.fullname" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["get", "watch", "list", "patch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - gatewayclasses
      - gatewayclasses/status
      - gateways
      - gateways/status
      - httproutes
      - httproutes/status
      - tlsroutes
      - tlsroutes/status
      - tcproutes
      - tcproutes/status
      - udproutes
      - udproutes/status
      - referencegrants
    verbs: ["get", "watch", "list", "patch", "update"]