{{- if .Values.controller.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "controller"
    spec:
      serviceAccountName: {{ include "bunkerweb.fullname" . }}
      containers:
        - name: bunkerweb-controller
          image: {{ .Values.controller.repository }}:{{ .Values.controller.tag }}
          imagePullPolicy: {{ .Values.controller.pullPolicy }}
          {{- with .Values.controller.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.controller.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.controller.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            # Mandatory for k8s integration
            - name: KUBERNETES_MODE
              value: "yes"
            - name: KUBERNETES_REVERSE_PROXY_SUFFIX_START
              value: "0"
            {{- if .Values.gatewayClass.enabled }}
            - name: KUBERNETES_GATEWAY_MODE
              value: "yes"
            {{- end }}
            - name: DATABASE_URI
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.settings.existingSecret }}
                  key: database-uri
              {{- else }}
              value: "{{ include "bunkerweb.databaseUri" . }}"
              {{- end }}
            - name: NAMESPACES
              value: "{{ .Values.settings.kubernetes.namespaces }}"
            - name: KUBERNETES_INGRESS_CLASS
              value: "{{ .Values.settings.kubernetes.ingressClass }}"
            - name: KUBERNETES_DOMAIN_NAME
              value: "{{ .Values.settings.kubernetes.domainName }}"
            - name: KUBERNETES_IGNORE_ANNOTATIONS
              value: "{{ .Values.settings.kubernetes.ignoreAnnotations }}"
            {{- if .Values.controller.extraEnvs }}
            {{- toYaml .Values.controller.extraEnvs | nindent 12 }}
            {{- end }}
            {{- if .Values.ui.logs.enabled }}
            - name: LOG_TYPES
              value: "stderr syslog"
            - name: LOG_SYSLOG_ADDRESS
              value: "{{ include "bunkerweb.syslogAddress" . }}"
            {{- end }}
    {{- if .Values.controller.nodeSelector }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.controller.tolerations) (.Values.tolerations) }}
      tolerations:
      {{- if .Values.controller.tolerations }}
        {{- toYaml .Values.controller.tolerations | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.controller.imagePullSecrets) (.Values.imagePullSecrets) }}
      imagePullSecrets:
      {{- if .Values.controller.imagePullSecrets }}
        {{- toYaml .Values.controller.imagePullSecrets | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
    {{- end }}
{{- end }}
