{{- if and .Values.gatewayClass.enabled (or .Values.settings.ui.httpRoutes.enabled .Values.settings.api.httpRoutes.enabled) -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "bunkerweb.fullname" . }}-gateway
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
  {{- if or .Values.settings.ui.httpRoutes.extraAnnotations .Values.settings.api.httpRoutes.extraAnnotations }}
  annotations:
    {{- with .Values.settings.ui.httpRoutes.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.settings.api.httpRoutes.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ .Values.gatewayClass.name }}
  listeners:
    {{- if .Values.settings.ui.httpRoutes.enabled }}
    - name: ui-http
      protocol: HTTP
      port: 80
      {{- if .Values.settings.ui.httpRoutes.serverName }}
      hostname: {{ .Values.settings.ui.httpRoutes.serverName | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.settings.ui.httpRoutes.tlsSecretName }}
    - name: ui-https
      protocol: HTTPS
      port: 443
      {{- if .Values.settings.ui.httpRoutes.serverName }}
      hostname: {{ .Values.settings.ui.httpRoutes.serverName | quote }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.settings.ui.httpRoutes.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- end }}
    {{- if .Values.settings.api.httpRoutes.enabled }}
    - name: api-http
      protocol: HTTP
      port: 80
      {{- if .Values.settings.api.httpRoutes.serverName }}
      hostname: {{ .Values.settings.api.httpRoutes.serverName | quote }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- if .Values.settings.api.httpRoutes.tlsSecretName }}
    - name: api-https
      protocol: HTTPS
      port: 443
      {{- if .Values.settings.api.httpRoutes.serverName }}
      hostname: {{ .Values.settings.api.httpRoutes.serverName | quote }}
      {{- end }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.settings.api.httpRoutes.tlsSecretName }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
    {{- end }}
{{- end }}
