{{- if .Values.gatewayClass.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  controllerName: {{ .Values.gatewayClass.controller }}
{{- end }}