{{- if .Values.mariadb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
      bunkerweb.io/component: "mariadb"
  strategy:
    type: {{ default "RollingUpdate" .Values.mariadb.strategy }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        bunkerweb.io/component: "mariadb"
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.repository }}:{{ .Values.mariadb.tag }}
          imagePullPolicy: {{ .Values.mariadb.pullPolicy }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- if .Values.mariadb.args }}
          args:
            {{- toYaml .Values.mariadb.args | nindent 12 }}
          {{- end }}
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "{{ .Values.mariadb.config.randomRootPassword }}"
            - name: MARIADB_DATABASE
              value: "{{ .Values.mariadb.config.database }}"
            - name: MARIADB_USER
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: mariadb-user
              {{- else }}
              value: "{{ .Values.mariadb.config.user }}"
              {{- end }}
            - name: MARIADB_PASSWORD
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: mariadb-password
              {{- else }}
              value: "{{ .Values.mariadb.config.password }}"
              {{- end }}
          {{- if .Values.mariadb.extraEnvs }}
            {{- toYaml .Values.mariadb.extraEnvs | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: vol-db
      volumes:
        - name: vol-db
          persistentVolumeClaim:
            claimName: mariadb-{{ include "bunkerweb.fullname" . }}
    {{- if .Values.mariadb.nodeSelector }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.mariadb.tolerations) (.Values.tolerations) }}
      tolerations:
      {{- if .Values.mariadb.tolerations }}
        {{- toYaml .Values.mariadb.tolerations | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.mariadb.imagePullSecrets) (.Values.imagePullSecrets) }}
      imagePullSecrets:
      {{- if .Values.mariadb.imagePullSecrets }}
        {{- toYaml .Values.mariadb.imagePullSecrets | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
    {{- end }}
{{- end }}
