{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
      bunkerweb.io/component: "redis"
  strategy:
    type: {{ default "RollingUpdate" .Values.redis.strategy }}
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        bunkerweb.io/component: "redis"
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.repository }}:{{ .Values.redis.tag }}
          imagePullPolicy:  {{ .Values.redis.pullPolicy }}
          {{- if .Values.redis.useConfigFile }}
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          {{- end }}
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: redis-password
              {{- else }}
              value: "{{ .Values.redis.config.password }}"
              {{- end }}
          {{- if .Values.redis.extraEnvs }}
            {{- toYaml .Values.redis.extraEnvs | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12}}
          {{- end }}
          volumeMounts:
          {{- if .Values.redis.useConfigFile }}
          - name: redis-config
            mountPath: /usr/local/etc/redis/
            readOnly: true
          {{- end }}
          - name: redis-data
            mountPath: /data       
      volumes:
      {{- if .Values.redis.useConfigFile }}
      - name: redis-config
        configMap:
          name: redis-config-{{ include "bunkerweb.fullname" . }}
      {{- end }}
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-{{ include "bunkerweb.fullname" . }}
    {{- if .Values.redis.nodeSelector }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.redis.tolerations) (.Values.tolerations) }}
      tolerations:
      {{- if .Values.redis.tolerations }}
        {{- toYaml .Values.redis.tolerations | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.redis.imagePullSecrets) (.Values.imagePullSecrets) }}
      imagePullSecrets:
      {{- if .Values.redis.imagePullSecrets }}
        {{- toYaml .Values.redis.imagePullSecrets | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
    {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}