{{- if .Values.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-{{ include "bunkerweb.fullname" . }}
  namespace: {{ include "bunkerweb.namespace" . }}
  labels:
    {{- include "bunkerweb.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "bunkerweb.selectorLabels" . | nindent 6 }}
      bunkerweb.io/component: "ui"
  template:
    metadata:
      labels:
        {{- include "bunkerweb.labels" . | nindent 8 }}
        {{- with .Values.ui.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        bunkerweb.io/component: "ui"
    spec:
      containers:
        - name: bunkerweb-ui
          image: {{ .Values.ui.repository }}:{{ .Values.ui.tag }}
          imagePullPolicy: {{ .Values.ui.pullPolicy }}
          {{- with .Values.ui.resources }}
          resources:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.ui.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.ui.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.ui.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}
          env:
            - name: DATABASE_URI
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.settings.existingSecret }}
                  key: database-uri
              {{- else }}
              value: "{{ include "bunkerweb.databaseUri" . }}"
              {{- end }}
            - name: ADMIN_USERNAME
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: admin-username
              {{- else }}
              value: "{{ .Values.settings.ui.adminUsername }}"
              {{- end }}
            - name: ADMIN_PASSWORD
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: admin-password
              {{- else }}
              value: "{{ .Values.settings.ui.adminPassword }}"
              {{- end }}
            - name: TOTP_SECRETS
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: totp-secrets
              {{- else }}
              value: "{{ .Values.settings.ui.totpSecrets }}"
              {{- end }}
            - name: FLASK_SECRET
              {{- if not (empty .Values.settings.existingSecret) }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.settings.existingSecret }}"
                  key: flask-secret
              {{- else }}
              value: "{{ .Values.settings.ui.flaskSecret }}"
              {{- end }}
            {{- if .Values.ui.logs.enabled }}
            - name: LOG_TYPES
              value: "stderr syslog"
            - name: LOG_SYSLOG_ADDRESS
              value: "{{ include "bunkerweb.syslogAddress" . }}"
            {{- end }}
            - name: OVERRIDE_ADMIN_CREDS
              value: "{{ .Values.settings.ui.overrideAdminCreds }}"
            {{- if .Values.ui.extraEnvs }}
              {{- toYaml .Values.ui.extraEnvs | nindent 12 }}
            {{- end }}
      {{- if .Values.ui.logs.enabled }}
          volumeMounts:
            - name: bunkerweb-logs
              mountPath: /var/log/bunkerweb
        - name: bunkerweb-syslog
          image: {{ .Values.ui.logs.repository }}:{{ .Values.ui.logs.tag }}
          imagePullPolicy: {{ .Values.ui.logs.pullPolicy }}
        {{- range .Values.scheduler.extraEnvs }}
        {{- if eq .name "TZ" }}
          env:
            - name: TZ
              value: "{{ .value }}"
        {{- end }}
        {{- end }}
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              - NET_BROADCAST
              - NET_RAW
              - DAC_READ_SEARCH
              - DAC_OVERRIDE
              - CHOWN
              - SYSLOG
          volumeMounts:
            - name: bunkerweb-logs
              mountPath: /var/log/bunkerweb
            - name: bunkerweb-syslog-config
              mountPath: /etc/syslog-ng/syslog-ng.conf
              subPath: syslog-ng.conf
              readOnly: true
      volumes:
      - name: bunkerweb-logs
        persistentVolumeClaim:
          claimName: ui-{{ include "bunkerweb.fullname" . }}
      - name: bunkerweb-syslog-config
        configMap:
          name: ui-{{ include "bunkerweb.fullname" . }}
      {{- end }}
    {{- if .Values.ui.nodeSelector }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- else if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.ui.tolerations) (.Values.tolerations) }}
      tolerations:
      {{- if .Values.ui.tolerations }}
        {{- toYaml .Values.ui.tolerations | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if or (.Values.ui.imagePullSecrets) (.Values.imagePullSecrets) }}
      imagePullSecrets:
      {{- if .Values.ui.imagePullSecrets }}
        {{- toYaml .Values.ui.imagePullSecrets | nindent 6 }}
      {{- else }}
        {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
    {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}